/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajedrez;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Jose
 */
public class Tablero extends javax.swing.JFrame {

    
    private Casilla[][] casillas;
    private Pieza[][] piezas;
    private javax.swing.JPanel jPanelTablero;

    public Tablero(int x, int y, int anchoCasilla) {
        setLayout(null);        
        initComponents();

        int margen = 5;
        setSize(x+(anchoCasilla+margen)*8+25, y+(anchoCasilla+margen)*8+50);
        setLocation(400, 200);

        // creación del tablero
        jPanelTablero = new javax.swing.JPanel();
        jPanelTablero.setLocation(x, y);
        jPanelTablero.setSize((anchoCasilla+margen)*8, (anchoCasilla+margen)*8);
        this.add(jPanelTablero);
               
        // crear las casillas
        casillas = new Casilla[8][8];                    
        for(int i=0; i<8; i++)
        {
            for(int j=0; j<8; j++)
            {
                casillas[i][j] = new Casilla(i, j, (i%2+(8*i+j)%2)!=1, anchoCasilla);
                jPanelTablero.add(casillas[i][j].getRepresentacionVisual());
            }
        }           
        
        // ...y las piezas
        piezas = new Pieza[2][16];
        for(int color=0; color<2; color++)
        {
            // para cada color, creamos las 16 piezas...
            // primero las figuras
            piezas[color][0] = new Pieza(Pieza.tipoPieza.torre, color==1);
            piezas[color][1] = new Pieza(Pieza.tipoPieza.caballo, color==1);
            piezas[color][2] = new Pieza(Pieza.tipoPieza.alfil, color==1);
            piezas[color][3] = new Pieza(Pieza.tipoPieza.rey, color==1);
            piezas[color][4] = new Pieza(Pieza.tipoPieza.reina, color==1);
            piezas[color][5] = new Pieza(Pieza.tipoPieza.alfil, color==1);
            piezas[color][6] = new Pieza(Pieza.tipoPieza.caballo, color==1);
            piezas[color][7] = new Pieza(Pieza.tipoPieza.torre, color==1);
                      
            // luego los peones
            for(int j=8; j<16; j++)
                piezas[color][j] = new Pieza(Pieza.tipoPieza.peon, color==1);
        } 
        
        // colocamos las piezas sobre el tablero
        for(int i=0; i<8; i++)
        {
            casillas[0][i].setPiezaQueOcupa(piezas[1][i]);
            casillas[1][i].setPiezaQueOcupa(piezas[1][i+8]);
            casillas[6][i].setPiezaQueOcupa(piezas[0][i+8]);
            casillas[7][i].setPiezaQueOcupa(piezas[0][i]);       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
